### PR TITLE
XML:Display:TRACK MSM8916

### PR DESCRIPTION
**Pull request by hpnightowl**
*Track these else will create error While compiling for msm8916

### CODE REVIEW

**Comment by Subinsmani** [comment]
Push Ur patch to gerrit pls http://gerrit.pixysos.org

**Comment by hpnightowl** [comment]
ok gerrit newly open ?

**Comment by Subinsmani** [comment]
Nah Its Already there, but 2 days back due to technical issue Gerrit database get cleaned. so it look clean now :D

**Comment by hpnightowl** [comment]
ok

**Comment by hpnightowl** [comment]
@Subinsmani your email confirmation is not working i can't verify mt email

**Comment by hpnightowl** [comment]
http://gerrit.pixysos.org/c/PixysOS/manifest/+/15 has been submitted here :)

**Pull request closed without merging**
